num1 = float(input("Enter the value for num1: "))
num2 = float(input("Enter the value for num2: "))
num3 = float(input("Enter the value for num3: "))
print(f"The value of num1 is {num1}, and it is of the type {type(num1)}.")
print(f"The value of num2 is {num2}, and it is of the type {type(num2)}.")
print(f"The value of num3 is {num3}, and it is of the type {type(num3)}.")
print()
print(f"The sum of num1 and num2 is {num1 + num2}.")
print(f"The difference of num1 and num2 is {num1 - num2}.")
print(f"The product of num1 and num2 is {num1 * num2}.")
print(f"The division of num1 by num2 is {num1 / num2}.")
print()
result1 = num1 + num2 * num3
print(f"Result without parentheses (num1 + num2 * num3): {result1}")

result2 = (num1 + num2) * num3
print(f"Result with parentheses ((num1 + num2) * num3): {result2}")
print()
print(f"Is num1 greater than num2? {num1 > num2}")
print(f"Is num2 less than or equal to num3? {num2 <= num3}")
print(f"Is num3 equal to num1? {num3 == num1}")